version: '3.8'
services:
    gw_api:
        container_name: teglon_api
        build: .
        image: "davecoulter/teglon:0.0.1"
#        command: python /app/web/manage.py run -h 0.0.0.0
        command: gunicorn --bind 0.0.0.0:5000 web.manage:app --timeout 1200
        volumes:
            - ${VOL_APP}:/app
            - ${VOL_CDBS}:/cdbs
        ports:
          - 5000:5000
        links:
            - gw_db
        environment:
          PYSYN_CDBS: /cdbs/
          FLASK_APP: web/project/__init__.py
          FLASK_DEBUG: 1
        depends_on:
          gw_db:
            condition: service_healthy
    gw_db:
        container_name: teglon_db
        image: "mysql:8.0.25"
        ports:
            - ${LOCAL_DB_PORT}:3306
        volumes:
            - ${VOL_DB}:/var/lib/mysql
            - ./db_init/db_configuration:/etc/mysql/conf.d
            - ./db_init/init.sql:/docker-entrypoint-initdb.d/1.sql
            - ./db_init/teglon_O4.sql:/docker-entrypoint-initdb.d/2.sql
            - ./db_init/angsep.sql:/docker-entrypoint-initdb.d/3.sql
            - ./db_init/teglon_users.sql:/docker-entrypoint-initdb.d/4.sql
            - ${VOL_DB_LOG}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PWD}
        healthcheck:
          test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
          timeout: 20s
          retries: 10
    gw_script:
      container_name: teglon_script
      build: .
      image: "davecoulter/teglon:0.0.1"
      volumes:
        - ${VOL_APP}:/app
        - ${VOL_CDBS}:/cdbs
      links:
        - gw_db
      environment:
        PYSYN_CDBS: /cdbs/
      depends_on:
        gw_db:
          condition: service_healthy
    nginx:
      build:
          context: .
          dockerfile: Dockerfile.nginx
      volumes:
        - ${VOL_APP}:/app/
      ports:
        - 1337:80
      depends_on:
        - gw_api